<a href="https://colab.research.google.com/github/camilamurillo1/Extraccion-de-datos-/blob/main/Actividad1_2ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO XLSX

In [68]:
#Convertir en dataframe
df=pd.read_excel("DatosFacturación.xlsx")
df

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218.0,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [ ]:
#Verificamos información del DataFrame
df.info()

In [55]:
#Imprimo los primeros 5 registro del dataframe
df.head(3)

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.0,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.0,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.0,0.0,0

In [69]:
filtro1=df[(df["CVE_CLPV"] > 1000) & (df["CVE_CLPV"] < 2000)]
filtro1

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

In [70]:
filtro1.to_csv("Filtro1.csv")

from google.colab import files 
files.download("Filtro1.csv")

In [10]:
#Filtro not "&"
filtro2=df[~(df["CVE_VEND"] == "5") & ~(df["CVE_VEND"] == "4")]
filtro2

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [ ]:
filtro2.to_csv("Filtro2.csv")

from google.colab import files 
files.download("Filtro2.csv")

In [22]:
#Filtro o "|"
filtro4=df[(df["CAN_TOT"] < 5951.7) | (df["STATUS"] == "E")]
filtro4

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [ ]:
filtro4.to_csv("Filtro4.csv")

from google.colab import files 
files.download("Filtro4.csv")

In [72]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

Saving DatosFacturación.xlsx to DatosFacturación (3).xlsx

In [73]:
df1= pd.read_excel("DatosFacturación.xlsx", index_col=3) #indicas que columna quieres que sea como indice 
df1

,CVE_DOC,CVE_CLPV,STATUS,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
CVE_VEND,,,,,,,,,,,
1.0,F29414,2465.0,C,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1.0,F29415,3926.0,C,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
1.0,F29416,3926.0,C,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
1.0,F29417,3926.0,C,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
2.0,F29418,6813.0,C,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
2.0,F40306,8842.0,E,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
2.0,F40307,6218.0,E,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
2.0,F40308,5926.0,E,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
2.0,F40309,361.0,E,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
2.0,F40310,3011.0,E,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [49]:
#Filtro por columnas

filtro5=df1.iloc[ 1:11 , [0,5,6,8]]  #Columnas no consecutivas 
filtro5

                    CVE_DOC            FECHA_ENT  FECHA_VEN   CAN_TOT
FECHAELAB
2019-09-03 09:55:14  F29415  2019-09-03 00:00:00 2019-10-03  1550.000
2019-09-03 13:25:33  F29416  2019-09-03 00:00:00 2019-10-03  1550.000
2019-09-03 13:33:23  F29417  2019-09-03 00:00:00 2019-10-03  1550.000
2019-09-03 14:23:45  F29418  2019-09-03 00:00:00 2019-09-03  2435.440
2019-09-04 09:15:12  F29419  2019-09-04 00:00:00 2019-09-19  3979.998
2019-09-04 10:53:53  F29420  2019-09-04 00:00:00 2019-09-04   402.590
2019-09-04 10:56:44  F29421  2019-09-04 00:00:00 2019-09-04   402.590
2019-09-04 11:14:44  F29422  2019-09-02 00:00:00 2019-09-04  1606.740
2019-09-04 12:23:05  F29423  2019-09-02 00:00:00 2019-09-04  1144.430
2019-09-04 12:36:15  F29424  2019-09-03 00:00:00 2019-09-04   462.310

In [ ]:
filtro5.to_csv("Filtro5.csv")

from google.colab import files 
files.download("Filtro5.csv")

In [30]:
#Filtro por filas

filtro6= df.iloc[7001:7099,: ]           #Filas consecutivas, : es para que te den todas las columnas 
 
filtro6

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,F36417,5271,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06 00:00:00,2021-11-14,NaT,8555.24,0.0,0
7002,F36418,5746,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14 00:00:00,2021-10-15,NaT,620.77,0.0,0
7003,F36419,2163,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15 00:00:00,2021-10-15,NaT,560.00,0.0,0
7004,F36420,1429,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15 00:00:00,2021-12-14,NaT,23625.00,0.0,0
7005,F36421,5039,E,1.0,2021-10-15 09:07:07.103,2021-10-15,2021-10-08 00:00:00,2022-01-13,NaT,3308.78,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7094,F36510,4480,E,2.0,2021-10-27 13:01:57.527,2021-10-27,2021-10-21 00:00:00,2021-11-11,NaT,2904.40,0.0,0
7095,F36511,4480,E,2.0,2021-10-27 13:07:43.223,2021-10-27,2021-10-27 00:00:00,2021-11-11,NaT,1137.50,0.0,0
7096,F36512,8186,E,2.0,2021-10-27 13:22:23.980,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,94.84,0.0,0
7097,F36513,4403,E,2.0,2021-10-27 13:35:40.677,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,847.00,0.0,0
7098,F36514,5589,E,2.0,2021-10-27 14:02:54.630,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,965.00,0.0,0

In [31]:
filtro6.to_csv("Filtro6.csv")

from google.colab import files 
files.download("Filtro6.csv")

In [76]:
df2=df.set_index("CVE_VEND")
filtro7=df2.loc[[1,2],["FECHAELAB"]]
filtro7

                       FECHAELAB
CVE_VEND
1.0      2019-09-03 08:58:42.000
1.0      2019-09-03 09:55:14.000
1.0      2019-09-03 13:25:33.000
1.0      2019-09-03 13:33:23.000
1.0      2019-09-04 09:15:12.000
...                          ...
2.0      2023-03-06 16:09:39.013
2.0      2023-03-06 16:38:42.933
2.0      2023-03-06 17:02:33.390
2.0      2023-03-07 12:43:49.567
2.0      2023-03-07 12:45:58.407

[8665 rows x 1 columns]

In [77]:
filtro7.to_csv("Filtro7.csv")

from google.colab import files 
files.download("Filtro7.csv")